import {createElement} from 'lwc';
import Today from 'c/homepageTodaysMeeting';
import Calendar from 'c/homepageCalendarMeetings';
import Modal from 'c/homepageViewAllMeetings';
const RealDate = Date; const fixed=RealDate.parse('2026-09-22T10:00:00Z');
window.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed;}};
const params=new URLSearchParams(location.search);const surface=params.get('surface')||'today';
const el=createElement('c-preview',{is:surface==='calendar'?Calendar:surface==='modal'?Modal:Today});
el.scopeConfig={sellerId:'005000000000001AAA',recordTypeIds:['012000000000001AAA','012000000000002AAA']};
el.displayZone='UTC';el.maxVisibleMeetings=2;el.selectedDate='2026-09-22';el.initialDate='2026-09-22';
if(params.get('expanded'))el.displayMode='expanded';
el.initialView=params.get('view')||'week';
document.querySelector('#mount').append(el);
